name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: |
        touch .env
        echo "CONSUMERKEY=${{ secrets.CONSUMERKEY }}" >> .env
        echo "CONSUMERSECRET=${{ secrets.CONSUMERSECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
        echo "TOKEN=${{ secrets.TOKEN }}" >> .env
    - run: pm2 restart api
